
package com.bratkov.consumingbooking.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FlightsPort", targetNamespace = "https://lab.com/flight")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightsPort {


    /**
     * 
     * @param getAvailableFlightsRequest
     * @return
     *     returns com.bratkov.consumingbooking.wsdl.GetAvailableFlightsResponse
     */
    @WebMethod
    @WebResult(name = "getAvailableFlightsResponse", targetNamespace = "http://lab.com/flight", partName = "getAvailableFlightsResponse")
    public GetAvailableFlightsResponse getAvailableFlights(
        @WebParam(name = "getAvailableFlightsRequest", targetNamespace = "http://lab.com/flight", partName = "getAvailableFlightsRequest")
        GetAvailableFlightsRequest getAvailableFlightsRequest);

    /**
     * 
     * @param getFlightsRequest
     * @return
     *     returns com.bratkov.consumingbooking.wsdl.GetFlightsResponse
     */
    @WebMethod
    @WebResult(name = "getFlightsResponse", targetNamespace = "http://lab.com/flight", partName = "getFlightsResponse")
    public GetFlightsResponse getFlights(
        @WebParam(name = "getFlightsRequest", targetNamespace = "http://lab.com/flight", partName = "getFlightsRequest")
        GetFlightsRequest getFlightsRequest);

}
