
package com.bratkov.consumingbooking.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FlightsPortService", targetNamespace = "https://lab.com/flight", wsdlLocation = "http://localhost:8081/ws/flights.wsdl")
public class FlightsPortService
    extends Service
{

    private final static URL FLIGHTSPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTSPORTSERVICE_EXCEPTION;
    private final static QName FLIGHTSPORTSERVICE_QNAME = new QName("https://lab.com/flight", "FlightsPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/flights.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTSPORTSERVICE_WSDL_LOCATION = url;
        FLIGHTSPORTSERVICE_EXCEPTION = e;
    }

    public FlightsPortService() {
        super(__getWsdlLocation(), FLIGHTSPORTSERVICE_QNAME);
    }

    public FlightsPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTSPORTSERVICE_QNAME, features);
    }

    public FlightsPortService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTSPORTSERVICE_QNAME);
    }

    public FlightsPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTSPORTSERVICE_QNAME, features);
    }

    public FlightsPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightsPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightsPort
     */
    @WebEndpoint(name = "FlightsPortSoap11")
    public FlightsPort getFlightsPortSoap11() {
        return super.getPort(new QName("https://lab.com/flight", "FlightsPortSoap11"), FlightsPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightsPort
     */
    @WebEndpoint(name = "FlightsPortSoap11")
    public FlightsPort getFlightsPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("https://lab.com/flight", "FlightsPortSoap11"), FlightsPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTSPORTSERVICE_EXCEPTION!= null) {
            throw FLIGHTSPORTSERVICE_EXCEPTION;
        }
        return FLIGHTSPORTSERVICE_WSDL_LOCATION;
    }

}
